stages:
  - deploy

deploy_to_vps:
  stage: deploy
  only:
    - develop
  script:
    - echo "$VPS_USER"
    - echo "$VPS_HOST"
    - apt-get update -y && apt-get install -y openssh-client
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$VPS_SSH_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
    - cat ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - echo "$VPS_SSH_KEY"
    - ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts || true
    # Deploy to VPS
    - ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "echo 'SSH Connection Successful'"
    - ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
      set -e
      cd ~/lms/lms-fe
      echo "🔙 Creating backup of current build..."
      rm -rf .next_backup
      cp -r .next .next_backup || echo "⚠️ No previous build found, skipping backup."
      git pull origin develop
      cp .env.example .env
      npm install -f
      echo "🚧 Building the app..."
      if npm run build; then
      echo "✅ Build successful!"
      pm2 reload lms-web --update-env
      else
      echo "❌ Build failed! Rolling back to previous version..."
      rm -rf .next
      mv .next_backup .next || echo "⚠️ No backup found, rollback failed."
      pm2 reload lms-web --update-env
      exit 1
      fi
    - EOF

  environment:
    name: develop
