stages:
  - deploy

deploy_to_vps:
  stage: deploy
  only:
    - develop
  script:
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$VPS_SSH_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
    - echo "VPS_USER: $VPS_USER"
    - echo "VPS_HOST: $VPS_HOST"
    - echo "VPS_SSH_KEY length: ${#VPS_SSH_KEY}"
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts
    - ssh $VPS_USER@$VPS_HOST "echo 'SSH Connection Successful'"
    # Deploy to VPS
    - ssh $VPS_USER@$VPS_HOST << 'EOF'
      cd ~/apps/nextjs-app
      git pull origin develop
      npm install -f
      npm run build
      pm2 delete lms-web
      pm2 start "npm run start" --name lms-web
      pm2 save
      pm2 startup
      EOF

  environment:
    name: production
