stages:
  - deploy

deploy_to_vps:
  stage: deploy
  only:
    - develop
  script:
    - apt-get update -y && apt-get install -y openssh-client
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$VPS_SSH_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
    - cat ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - echo "$VPS_SSH_KEY"
    - ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts || true
    # Deploy to VPS
    - ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "echo 'SSH Connection Successful'"
    - ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
      cd ~/lms/lms-fe
      git pull origin develop
      npm install -f
      npm run build
      pm2 delete lms-web
      pm2 start "npm run start" --name lms-web
      pm2 save
      pm2 startup
      EOF

  environment:
    name: develop
